<?php

namespace Cruiser\ShortenerUrlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShortenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortenerRepository extends EntityRepository
{
}
